site_name: MAGPAI - MAG Prototype AI
site_description: AI Under the Covers Lab
site_author: Vasilis Katsoulis

theme:
  name: material

nav:
  - Demo:
      - Tokenizer Lab: demo/tokenizer_lab.md
      - Embedding Lab: demo/embedding_lab.md
      - Chatbot Demo: demo/magpai_chatbot_v0_1.md
