site_name: MAGPAI - MAG Prototype AI
site_description: AI Under the Covers Lab
site_author: Vasilis Katsoulis
dev_addr: 0.0.0.0:8000

theme:
  name: material

nav:
  - Demo:
      - Tokenizer Lab: demo/tokenizer_lab.md
      - Embedding Lab: demo/embedding_lab.md
      - Vocabulary training: demo/Vocabulary_Training_Demo_v2_10.html
      - Vision Vocabulary Training: demo/vision_vocabulary_demo_v1_1.html
      - Chatbot Demo: demo/magpai_chatbot_v0_1.md
      - Neural Network Training v1: demo/MAGPAI_Weight_Bias_Visual_Trainer_v1.0.html
      - Neural Network Training v2: demo/MAGPAI_Tiny_ANN_Trainer_v2.0.html
      - Vision Neural Network Training: demo/vision_neural_network_demo_v1_11.html
