# =============================================================================
# Module Name: magpai_agent_email_server_v1_1.py
# Author: javaboy-vk
# Date: 2026-06-04
# Version: 1.1
# Description:
#   Local MAGPAI Agent demo server. Serves the MAGPAI Agent Demo v1.1 HTML page
#   and provides an /api/send-email endpoint that sends the branded MAGPAI email
#   through an SMTP server configured with environment variables.
# =============================================================================

from __future__ import annotations

import json
import os
import socket
import smtplib
import subprocess
import sys
import threading
import time
from email.message import EmailMessage
from http.server import HTTPServer, SimpleHTTPRequestHandler
from pathlib import Path
from typing import Any

HOST = "127.0.0.1"
DEMO_HTML = "magpai-agent-demo-v1.1.html"
DEFAULT_TO = "vasilis.katsoulis@mail.com"
SCRIPT_DIR = Path(__file__).resolve().parent
REPO_ROOT = SCRIPT_DIR.parents[2]
DEMO_DIR = REPO_ROOT / "docs" / "demo"
ENV_FILE = SCRIPT_DIR / "magpai-agent-demo-v1.1.env"


def load_env_file(path: Path) -> None:
    if not path.exists():
        return

    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        name, value = line.split("=", 1)
        os.environ[name.strip()] = value.strip().strip('"')


load_env_file(ENV_FILE)
PORT = int(os.environ.get("MAGPAI_DEMO_PORT", "8088"))


def get_required_env(name: str) -> str:
    value = os.environ.get(name, "").strip()
    if not value:
        raise RuntimeError(f"Missing required environment variable: {name}")
    return value


def build_email_payload(data: dict[str, Any]) -> EmailMessage:
    smtp_user = get_required_env("MAGPAI_SMTP_USER")
    from_email = os.environ.get("MAGPAI_SMTP_FROM", smtp_user).strip() or smtp_user
    from_name = os.environ.get("MAGPAI_SMTP_FROM_NAME", "MAGPAI Agent").strip() or "MAGPAI Agent"
    if "@" not in from_email or "." not in from_email.split("@", 1)[-1]:
        raise RuntimeError(
            "MAGPAI_SMTP_FROM must be an email address, for example "
            "magpai-demo@example.invalid. Put the display name in "
            "MAGPAI_SMTP_FROM_NAME."
        )

    to_email = str(data.get("to") or DEFAULT_TO)
    subject = str(data.get("subject") or "MAGPAI Agent Report: Chicago Sales Are Up")

    city = str(data.get("city", "Chicago"))
    previous_period = str(data.get("previousPeriod", "May"))
    current_period = str(data.get("currentPeriod", "June"))
    previous_sales = float(data.get("previousSales", 10.2))
    current_sales = float(data.get("currentSales", 11.4))
    difference = float(data.get("difference", current_sales - previous_sales))
    growth = float(data.get("growth", (difference / previous_sales) * 100))

    text_body = f"""MAGPAI Agent Report

Summary:
{city} MAG sales are up.

{previous_period}: ${previous_sales:.1f}M
{current_period}: ${current_sales:.1f}M
Difference: +${difference:.1f}M
Growth: +{growth:.1f}%

Generated by: MAGPAI Agent Demo v1.1
"""

    html_body = f"""
    <html>
      <body style="font-family: Segoe UI, Arial, sans-serif; background:#eef3f8; padding:24px; color:#132238;">
        <div style="max-width:720px; margin:0 auto; background:#ffffff; border-radius:18px; overflow:hidden; border:1px solid #b7c7d9;">
          <div style="background:linear-gradient(90deg,#132238,#1f6feb); color:#ffffff; padding:22px 26px;">
            <div style="font-size:28px; font-weight:900; letter-spacing:1px;">MAGPAI</div>
            <div style="font-size:14px; opacity:.92;">MAG AI Agent Platform</div>
          </div>
          <div style="padding:24px 26px;">
            <h2 style="margin-top:0; color:#132238;">Chicago Sales Trend Analysis</h2>
            <p style="font-size:16px; line-height:1.55;">
              <strong>{city} MAG sales are up.</strong> Sales increased from
              <strong>${previous_sales:.1f}M</strong> in {previous_period} to
              <strong>${current_sales:.1f}M</strong> in {current_period}.
            </p>
            <table style="width:100%; border-collapse:collapse; margin:18px 0;">
              <tr><td style="padding:10px; border-bottom:1px solid #dbeafe;">Previous Month</td><td style="padding:10px; border-bottom:1px solid #dbeafe; text-align:right;"><strong>${previous_sales:.1f}M</strong></td></tr>
              <tr><td style="padding:10px; border-bottom:1px solid #dbeafe;">Current Month</td><td style="padding:10px; border-bottom:1px solid #dbeafe; text-align:right;"><strong>${current_sales:.1f}M</strong></td></tr>
              <tr><td style="padding:10px; border-bottom:1px solid #dbeafe;">Difference</td><td style="padding:10px; border-bottom:1px solid #dbeafe; text-align:right;"><strong>+${difference:.1f}M</strong></td></tr>
              <tr><td style="padding:10px;">Growth</td><td style="padding:10px; text-align:right;"><strong>+{growth:.1f}%</strong></td></tr>
            </table>
            <div style="background:#dcfce7; color:#1f9d55; padding:14px 16px; border-radius:12px; font-weight:800;">
              Agent action completed: email sent by MAGPAI Agent Demo v1.1.
            </div>
          </div>
        </div>
      </body>
    </html>
    """

    message = EmailMessage()
    message["From"] = f"{from_name} <{from_email}>"
    message["To"] = to_email
    message["Subject"] = subject
    message.set_content(text_body)
    message.add_alternative(html_body, subtype="html")
    return message


def send_email(data: dict[str, Any]) -> dict[str, Any]:
    smtp_host = get_required_env("MAGPAI_SMTP_HOST")
    smtp_port = int(os.environ.get("MAGPAI_SMTP_PORT", "587"))
    smtp_user = get_required_env("MAGPAI_SMTP_USER")
    smtp_password = get_required_env("MAGPAI_SMTP_PASSWORD")
    use_ssl = os.environ.get("MAGPAI_SMTP_SSL", "false").lower() in {"1", "true", "yes"}
    timeout = int(os.environ.get("MAGPAI_SMTP_TIMEOUT", "10"))

    message = build_email_payload(data)

    try:
        if use_ssl:
            with smtplib.SMTP_SSL(smtp_host, smtp_port, timeout=timeout) as server:
                server.login(smtp_user, smtp_password)
                server.send_message(message)
        else:
            with smtplib.SMTP(smtp_host, smtp_port, timeout=timeout) as server:
                server.ehlo()
                server.starttls()
                server.ehlo()
                server.login(smtp_user, smtp_password)
                server.send_message(message)
    except (socket.timeout, TimeoutError) as exc:
        mode = "implicit SSL" if use_ssl else "STARTTLS"
        raise RuntimeError(
            f"SMTP timed out while connecting to {smtp_host}:{smtp_port} using {mode}. "
            "The host/port is reachable only if the SMTP server sends a greeting and accepts "
            "the selected TLS mode from this network."
        ) from exc

    return {"ok": True, "to": message["To"], "subject": message["Subject"]}


def restart_server_later(server: HTTPServer) -> None:
    script = Path(__file__).resolve()
    command = f'timeout /t 2 /nobreak >nul & "{sys.executable}" "{script}"'
    subprocess.Popen(
        command,
        cwd=str(REPO_ROOT),
        shell=True,
        creationflags=getattr(subprocess, "CREATE_NEW_PROCESS_GROUP", 0),
    )
    time.sleep(0.2)
    server.shutdown()
    server.server_close()


class MagpaiDemoHandler(SimpleHTTPRequestHandler):
    def _add_cors_headers(self) -> None:
        self.send_header("Access-Control-Allow-Origin", "*")
        self.send_header("Access-Control-Allow-Methods", "GET, POST, OPTIONS")
        self.send_header("Access-Control-Allow-Headers", "Content-Type")

    def end_headers(self) -> None:
        self._add_cors_headers()
        super().end_headers()

    def do_GET(self) -> None:
        if self.path == "/api/health":
            self._send_json(200, {"ok": True, "status": "running"})
            return
        if self.path in {"/", "/index.html"}:
            self.path = f"/{DEMO_HTML}"
        return super().do_GET()

    def do_OPTIONS(self) -> None:
        self.send_response(204)
        self.end_headers()

    def do_POST(self) -> None:
        if self.path == "/api/restart":
            self._send_json(202, {"ok": True, "status": "restarting"})
            threading.Thread(
                target=restart_server_later,
                args=(self.server,),
                daemon=False,
            ).start()
            return

        if self.path != "/api/send-email":
            self.send_error(404, "Not Found")
            return

        try:
            length = int(self.headers.get("Content-Length", "0"))
            payload = self.rfile.read(length).decode("utf-8")
            data = json.loads(payload or "{}")
            result = send_email(data)
            self._send_json(200, result)
        except Exception as exc:  # Presentation demo: return readable configuration/runtime errors.
            self._send_json(500, {"ok": False, "error": str(exc)})

    def _send_json(self, status: int, payload: dict[str, Any]) -> None:
        body = json.dumps(payload).encode("utf-8")
        self.send_response(status)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)


def main() -> None:
    os.chdir(DEMO_DIR)
    print(f"MAGPAI Agent Demo v1.1 running at http://{HOST}:{PORT}")
    print(f"Serving HTML from: {DEMO_DIR}")
    print(f"Loading SMTP config from: {ENV_FILE}")
    print("Press Ctrl+C to stop.")
    HTTPServer((HOST, PORT), MagpaiDemoHandler).serve_forever()


if __name__ == "__main__":
    main()
